<div class="cssContentMiddle grid_16">
    <h1><?= $this->translate('Mailrobot of') ?> <?= $this->html('domain/name') ?></h1>
    <div class="cssDetailPadding30 cssForm grid_16">
        <div class="cssFormBoxLong grid_16">
            <form action="<?= $this->url(array($this->html('domain/name')), 'mazelab-vpopqmail_addMailRobot') ?>" method="post">

                <dl class="grid_16 cssNewPopaccountRow1">
                    <?= $this->form->user ?>
                </dl>
                <dl class="grid_16 cssNewPopaccountRow2">
                    <?= $this->form->domainId ?>
                </dl>

                <p class="ui-icon ui-icon-info cssInfoText jsInfo"></p>
                <dl class="grid_16">
                    <?= $this->form->status ?>
                </dl>
                <h6>
                    <?= $this->translate('Please enter your answer text') ?>
                </h6>
                <dl class="grid_16">
                    <?= $this->form->copyTo ?>
                </dl>
                <dl class="grid_16">
                    <?= $this->form->content ?>
                </dl>
                <div class="grid_16 cssButtonSpace cssButtonNew">
                    <input class="cssButton jsButton" id="jsCancelButton" type="reset" value="<?= $this->translate('cancel') ?>" />
                    <input class="cssButton jsButton" type="submit" value="<?= $this->translate('save') ?>" />
                </div>
                <p class="jsInfoText" style="display:none;">
                    <?= $this->translate('E-mails that are sent to the specified account, get an automatic reply using any text.') ?>
                </p>

            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('.jsButton').button();
        $(".selectFormMenu").selectmenu({
            appendTo: "div.cssFormBoxLong",
            style:'dropdown',
            width:'196',
            maxHeight: '400'
        });
        $('#domainId').removeAttr('disabled');
        $('#jsCancelButton').click(function() {
            location.href = '<?= $this->url(array(), 'mazelab-vpopqmail_specials'); ?>';
        });
        $('.jsInfo').qtip({
            content:{
                text:$(this).find('.jsInfoText').html(),
                title:{text:'Hinweis'}
            },
            show: {
                solo: true,
                when: {
                    event: 'click'
                }
            },
            hide: {
                when: {
                    event: 'unfocus'
                }
            },

            style:{
                width:{
                    max:400,
                    min:300
                },
                title:{
                    background:'#1AA8C9',
                    color:'#fff',
                    'font-size': 14
                },
                background:'#E7F7F8',
                color:'#3e3d3b',
                border:{
                    width:1,
                    color:'#1AA8C9',
                    radius:3
                },
                tip: { corner: 'topMiddle' }
            },
            position: { adjust: { x: -205, y: -5 } }
        })
    });
</script>