<div class="cssContentMiddle grid_16">
    <h1><?= $this->translate('Catch-all of') ?> <?= $this->html('domain/name') ?></h1>
    <div class="cssDetailPadding30 cssForm grid_16">
        <div class="cssFormBoxLong grid_16">
            <form action="<?= $this->url(array($this->html('domain/name')), 'mazelab-vpopqmail_editCatchAll') ?>" method="post">
                
                <dl class="grid_16">
                    <dt><?= $this->translate('domain name') ?></dt>
                    <dd><span><?= $this->html('domain/name') ?></span></dd>
                </dl>
                <h6>
                    <?= $this->translate('E-mails to unknown users will be') ?>
                </h6>
                <dl class="grid_16">
                    <dt>
                        <input type="radio" name="selectedBehavior"
                               value="<?= MazelabVpopqmail_Model_CatchAllManager::CATCH_ALL_BEHAVIOR_DELETE ?>"
                               <? if($this->selectedBehavior == MazelabVpopqmail_Model_CatchAllManager::CATCH_ALL_BEHAVIOR_DELETE ||
                                       !$this->selectedBehavior): ?>
                               checked="checked"
                               <? endif; ?>
                               />
                        <span></span>
                    </dt>
                    <dd>
                        <span><?= $this->translate('deleted') ?></span>
                    </dd>
                </dl>
                <dl class="grid_16">
                    <dt>
                        <input type="radio" name="selectedBehavior"
                               value="<?= MazelabVpopqmail_Model_CatchAllManager::CATCH_ALL_BEHAVIOR_SEND_TO_EMAIL ?>"
                               <? if($this->selectedBehavior == MazelabVpopqmail_Model_CatchAllManager::CATCH_ALL_BEHAVIOR_SEND_TO_EMAIL): ?>
                               checked="checked"
                               <? endif; ?>
                               />
                        <span><?= $this->translate('dispatched to email address') ?></span>
                    </dt>
                    <dd>
                        <?= $this->form->sendToEmail->renderViewHelper() ?>
                        <?= $this->form->sendToEmail->renderErrors()?>
                    </dd>
                </dl>
                <dl class="grid_16">
                    <dt>
                        <input <?= $this->selectHasEntry ? "" : "disabled=\"disabled\"" ?>  type="radio" name="selectedBehavior"
                               value="<?= MazelabVpopqmail_Model_CatchAllManager::CATCH_ALL_BEHAVIOR_MOVE_TO_ACCOUNT ?>"
                               <? if($this->selectedBehavior == MazelabVpopqmail_Model_CatchAllManager::CATCH_ALL_BEHAVIOR_MOVE_TO_ACCOUNT): ?>
                               checked="checked"
                               <? endif; ?>
                               />
                        <span><?= $this->translate('moved to the account') ?></span>
                    </dt>
                    <dd>
                        <?= $this->form->sendToAccount->renderViewHelper() ?>
                        <?= $this->form->sendToAccount->renderErrors()?>
                    </dd>
                </dl>
                <div class="grid_16 cssButtonSpace cssButtonNew">
                    <input class="cssButton jsButton" id="jsCancelButton" type="reset" value="<?= $this->translate('cancel') ?>" />
                    <input class="cssButton jsButton" type="submit" value="<?= $this->translate('save') ?>" />
                </div>
                
            </form>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        $('.jsButton').button();
        $('#jsCancelButton').click(function() {
            location.href = '<?= $this->url(array(), 'mazelab-vpopqmail_specials'); ?>';
        });
        $(".selectFormMenu").selectmenu({
            appendTo: "div.cssFormBoxLong",
            style:'dropdown',
            width:'196',
            maxHeight: '400'
        });
    });
</script>