<div class="cssContentMiddle grid_16">
    <div class="cssDomainFilter">
        <span><?= $this->translate('active filter') ?><b><?= $this->html('domain/name') ?></b></span>
        <a href="#" id="jsUnsetDomainFilter">
            <?= $this->translate('remove filter') ?>
        </a>
    </div>
    <h1 class="grid_16">
        <?= $this->translate('Specials of') ?>
        <?= $this->html('domain/name') ?>
    </h1>
    <?= $this->render('shared/searchfield.phtml'); ?>
    <div class="cssListing grid_16">
        <div class="grid_16 alpha omega cssHeaderList">
            <div class="grid_10 alpha omega">
                <div class="cssButtonNew grid_10">
                    <a class="jsButton" 
                       title="<?= $this->translate('create new special') ?>"
                       href="<?= $this->url(array('specialId' => 'test'), 'mazelab-vpopqmail_addspecial') ?>">
                        <?= $this->translate('create new special') ?>
                    </a>
                </div>
            </div>
            <div class="grid_6 alpha omega cssAction">
                <h3>
                     <?= $this->translate('actions') ?>
                </h3>
            </div>
        </div>
        <ul id="pagerContent" class="jsListSpecials">
            <?= $this->render('specials/domain.ajax.phtml'); ?>
        </ul>
        <div id="jsConfirmDelete" style="display:none;">
            <?= $this->translate('Shall the special really be deleted?') ?>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        $('#searchInput').mazeSearch('option', 'source', "<?= $this->url(array(), 'mazelab-vpopqmail_specials') ?>?format=html");
        
        $('#jsConfirmDelete').dialog({
            autoOpen: false,
            modal: true
        });

        $("#jsUnsetDomainFilter").click(function(){
            document.cookie = "domainId=; expires=" + new Date(0).toGMTString() +";";
            window.location = window.location.pathname;
            return false;
        });
        
        $('a.jsIconState').live('click', function() {
            var li = $(this).closest('li');
            
            $.ajax({
                url: $(this).attr('href') + '?format=json',
                success: function(data) {
                    if(data.special.status === true) {
                        $(li).find('.jsPagerStateDeactivate').show();
                        $(li).find('.jsPagerStateActivate').hide();
                    } else {
                        $(li).find('.jsPagerStateActivate').show();
                        $(li).find('.jsPagerStateDeactivate').hide();
                    }
                    setTooltips(data, li);
                }
            });
            
            return false;
        });
        $('a.jsIconDelete').live('click', function() {
            var elem = this;

            resetTooltips();
            $('#jsConfirmDelete').dialog({
                buttons : {
                    "<?= $this->translate('ok') ?>" : function() {
                        $.ajax({
                            url: $(elem).attr('href') + '?format=json',
                            success: function(data) {
                                
                                if(data.status === true) {
                                    setMessages(data);
                                } else {
                                    setTooltips(data, elem);
                                }
                            }
                        });
                        
                        $(this).dialog("close");
                    },
                    "<?= $this->translate('cancel') ?>" : function() {
                        $(this).dialog("close");
                    }
                }
            });

            $("#jsConfirmDelete").dialog("open");
            return false;
        });
    });
    
    function initButtons()
    {
        $('.jsButton').button();
        $('.jsIconTrash').button({
            icons: {
                primary: 'ui-icon-trash'
            },
            text: true
        });
        $('.jsIconEdit').button({
            icons: {
                primary: 'ui-icon-pencil'
            },
            text: false
        });
        $('.jsIconState').button({
            icons: {
                primary: 'ui-icon-circle-check'
            },
            text: false
        });
        $('.jsIconState.inactive').button({
            icons: {
                primary: 'ui-icon-circle-minus'
            },
            text: false
        });
        $('.jsIconDelete').button({
            icons: {
                primary: 'ui-icon-circle-close'
            },
            text: false
        });
    };
    
</script>