<div id="jsPassword" style="display:none;">
    <div class="cssPassword">
        <div class=cssPasswordTitle>
            <span>
                <?= $this->translate('password strength') ?>
            </span>
            <span class="jsPasswordDescription cssPasswordDescription">
                <?= $this->translate('very weakly') ?>
            </span>
        </div>

        <div class=cssPasswordStrength>
            <span class="jsPasswordStrength strength0"></span>
        </div>
        <span class="cssPasswordSupport">
            <?= $this->translate('Use at least 6 characters.') ?>
            <?= $this->translate('Use upper and lower case letters.') ?>
            <?= $this->translate('Include punctuation marks and / or numbers.') ?>
            <?= $this->translate('Include similar looking substitutions, such as the number zero for the letter O.') ?>
        </span>
    </div>
</div>
<script type="text/javascript">
    function passwordStrength(password)
    {
        var desc = new Array();
        desc[0] = "<?= $this->translate('very weakly') ?>";
        desc[1] = "<?= $this->translate('weak') ?>";
        desc[2] = "<?= $this->translate('better') ?>";
        desc[3] = "<?= $this->translate('medium') ?>";
        desc[4] = "<?= $this->translate('strong') ?>";
        desc[5] = "<?= $this->translate('very strong') ?>";

        var score   = 0;

        if (password.length === 0) return;

        //if password bigger than 6 give 1 point
        if (password.length > 6) score++;

        //if password has both lower and uppercase characters give 1 point	
        if ( ( password.match(/[a-z]/) ) && ( password.match(/[A-Z]/) ) ) score++;

        //if password has at least one number give 1 point
        if (password.match(/\d+/)) score++;

        //if password has at least one special caracther give 1 point
        if ( password.match(/.[!,@,#,$,%,^,&,*,?,_,~,-,(,)]/) )	score++;

        //if password bigger than 12 give another 1 point
        if (password.length > 12) score++;

        $('.jsPasswordDescription').html(desc[score]);
        $('.jsPasswordStrength').removeAttr('class').addClass('jsPasswordStrength').addClass("strength" + score);
    }
    
    $(document).ready(function() {
        $('.jsEditablePassword,#password').qtip({
            content: $('#jsPassword').html(),
            show: { when: { event: 'focus' }, solo: true },
            hide: 'unfocus',
            style: {
                tip: {
                    corner: 'topMiddle',
                    color: '#cccccc'
                }
            },
            position: {
                corner: {
                    target: 'bottomMiddle',
                    tooltip: 'topMiddle'
                }
            },
            api: {
                onRender: function(){
                    $self = this;
                    $self.elements.target.keydown(function(event) {
                        keyCode = (event.keyCode || event.which); 
                        if (keyCode === 9) $self.hide();
                    });
                }
            }
        });
    });
</script>
